// <auto-generated />
#pragma warning disable 414
namespace LaTeXBlocks.Word
{
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name = "FullTrust")]
    public sealed partial class ThisAddIn : Microsoft.Office.Tools.AddInBase
    {
        internal Microsoft.Office.Tools.CustomTaskPaneCollection CustomTaskPanes;
        internal Microsoft.Office.Tools.SmartTagCollection VstoSmartTags;
        internal Microsoft.Office.Interop.Word.Application Application;

        public ThisAddIn(global::Microsoft.Office.Tools.Word.ApplicationFactory factory, global::System.IServiceProvider serviceProvider)
            : base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
            Globals.Factory = factory;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize()
        {
            base.Initialize();
            Application = GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisAddIn = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            InitializeCachedData(); InitializeControls(); InitializeComponents(); InitializeData();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FinishInitialization() { InternalStartup(); OnStartup(); }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDataBindings() { BeginInitialization(); BindToData(); EndInitialization(); }

        private void InitializeCachedData() { if (DataHost != null && DataHost.IsCacheInitialized) DataHost.FillCachedData(this); }
        private void InitializeData() { }
        private void BindToData() { }
        private void BeginInitialization() { BeginInit(); CustomTaskPanes.BeginInit(); VstoSmartTags.BeginInit(); }
        private void EndInitialization() { VstoSmartTags.EndInit(); CustomTaskPanes.EndInit(); EndInit(); }
        private void InitializeControls()
        {
            CustomTaskPanes = Globals.Factory.CreateCustomTaskPaneCollection(null, null, "CustomTaskPanes", "CustomTaskPanes", this);
            VstoSmartTags = Globals.Factory.CreateSmartTagCollection(null, null, "VstoSmartTags", "VstoSmartTags", this);
        }
        private void InitializeComponents() { }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void OnShutdown() { VstoSmartTags.Dispose(); CustomTaskPanes.Dispose(); base.OnShutdown(); }
    }

    internal sealed partial class Globals
    {
        private static ThisAddIn thisAddIn;
        private static global::Microsoft.Office.Tools.Word.ApplicationFactory factory;
        private Globals() { }
        internal static ThisAddIn ThisAddIn
        {
            get => thisAddIn;
            set { if (thisAddIn != null) throw new global::System.NotSupportedException(); thisAddIn = value; }
        }
        internal static global::Microsoft.Office.Tools.Word.ApplicationFactory Factory
        {
            get => factory;
            set { if (factory != null) throw new global::System.NotSupportedException(); factory = value; }
        }
    }
}
